#config_version=5

##! mode: wdrops

mode:
  start_events: ball_starting
  stop_events: ball_drain
  priority: 150

# https://docs.missionpinball.org/en/latest/game_logic/shots/index.html

shots:
  # H or I lanes make White drops 5k and reset White drops
  HorI_shot:
    switch: s_H_rollover, s_I_rollover
    show_tokens:
      light: l_5k_wlit_white_drops   #uses default profile unlit | lit
    reset_events:
      ball_drain
  
variable_player:
  s_H_rollover_active:           #EBH & EB11k setup for extra ball on white_drops_complete
    EBH: 1
  player_bonus{current_player.bonus==11}:
    EB11k: 1
    
  ball_drain:
    EBH:
      int: 0
      action: set
    EB11k:
      int: 0
      action: set
    Rd5k:
      int: 0
      action: set      
      
  extra_ball_awarded:
    EBH:
      int: 0
      action: set
    EB11k:
      int: 0
      action: set 
      
  sw_dropWhite_active{device.shots.HorI_shot.state_name=='unlit'}:
    score: 500
  sw_dropWhite_active{device.shots.HorI_shot.state_name=='lit'}:
    score: 5000
  drop_target_bank_white_drops_down:    #completing White drops makes Red drops worth 5k
    Rd5k: 1
    
  sw_dw1_active{current_player.bonus_multiplier==4}:
    bonus_multiplier: 1

extra_balls:
  score_one:
    enabled: true
    max_per_game: 5  #somewhat arbitary, in theory infinite. ie one EB for each ball launched
    #light_events: 
    award_events: drop_target_bank_white_drops_down{current_player.EBH>0 and current_player.EB11k>0} 
    
# sound_player:
  # drop_target_bank_white_drops_down:
    # Iloveit:
      # action: play
      # volume: 1.0